version: '3.8'

services:
  web:
    build: .
    container_name: mynginx
    ports:
      - "8080:8080"
    volumes:
      - ./html:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always