FROM python:3.9-alpine

WORKDIR /app

# Копируем только необходимое из build-стадии
COPY --from=build /app /app

RUN adduser -D myuser && \
    chown -R myuser:myuser /app
USER myuser

ENV PATH="/app/venv/bin:$PATH"
ENV FLASK_APP=app.py
ENV FLASK_ENV=production

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0"]